Traceback (most recent call last):
  File "e:\uni\Invatare ADANCA\lab5\cod_curat.py", line 339, in <module>
    test_prediction()
  File "e:\uni\Invatare ADANCA\lab5\cod_curat.py", line 312, in test_prediction
    rgb_image[:, :, channel] = (matrix == channel + 1) * 255
ValueError: could not broadcast input array from shape (3,250,250) into shape (250,250)
Traceback (most recent call last):
  File "e:\uni\Invatare ADANCA\lab5\cod_curat.py", line 339, in <module>
    test_prediction()
  File "e:\uni\Invatare ADANCA\lab5\cod_curat.py", line 312, in test_prediction
    rgb_image[:, :, channel] = (matrix == channel + 1) * 255
ValueError: could not broadcast input array from shape (3,250,250) into shape (250,250)